# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_text', models.CharField(max_length=500)),
                ('email_id', models.IntegerField()),
                ('email_date', models.DateTimeField(verbose_name='email date')),
            ],
        ),
        migrations.CreateModel(
            name='email_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id_filtered', models.IntegerField()),
                ('email_date_new', models.DateTimeField(verbose_name='email date')),
                ('email_filtered', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_Spam.email')),
            ],
        ),
    ]
