# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 12:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_Spam', '0002_auto_20160405_1232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_new',
            old_name='email_new',
            new_name='email_filtered',
        ),
        migrations.AlterField(
            model_name='email_new',
            name='email_filtered',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='email_Spam.Email'),
        ),
    ]
